### ISSUE TITLE
Colour scheme doesn't match his tutorials

### ISSUE THREAD

**Issue by brettalton** [chrisburton/Jeffrey-Way-Theme#18]
Did the upstream Facebook colour scheme change or maybe Jeffrey changed his theme? They don't seem to match.

![screen shot 2017-05-08 at 8 27 08 pm](https://cloud.githubusercontent.com/assets/108411/25830727/cb2b6956-342c-11e7-9641-680448492a9a.png)

https://laracasts.com/series/laravel-from-scratch-2017/episodes/2?autoplay=true

**Comment by brettalton** [comment]
It appears he is using,
```
"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
"theme": "Material-Theme.sublime-theme",
```
should the Readme.md be updated?

**Comment by chrisburton** [comment]
> Did the upstream Facebook colour scheme change or maybe Jeffrey changed his theme?

Correct. It appears he changed his syntax theme based on the screenshot. 

> should the Readme.md be updated?

This particular theme I have compiled represents a specific video from his screencast. Jeffrey seems to jump between different text editors and IDE's as well as themes often. This repo will not be updated to reflect these dynamic changes however, people are certainly free to fork this repo and make those changes themselves.

**Comment by brettalton** [comment]
Makes complete sense. Thanks for making the repo in the first place.
