### ISSUE TITLE
what font is it?? it stayed the same.

### ISSUE THREAD

**Issue by sath26** [chrisburton/Jeffrey-Way-Theme#20]

**Comment by chrisburton** [comment]
The font used is Input as listed at the bottom of the readme. Is that what you're asking?

**Comment by sath26** [comment]
i dont know man! i expected the font to change as shown in the pictures of readme. but it is not. instead it was as it was before.

**Comment by chrisburton** [comment]
@sath26 Are you using SublimeLinter?

**Comment by chrisburton** [comment]
Closing due to lack of response.
